### ISSUE TITLE
Log the IP Address of the Request

### ISSUE THREAD

**Issue by clintcarter1999** [ocelot-collab/ocelot#150]
I have middleware added before app.UseOcelot().Wait() in my startup.cs.

         var configuration = new OcelotPipelineConfiguration
            {
                PreErrorResponderMiddleware = async (ctx, next) =>
                {
                    try
                    {
                        var logger = loggerFactory.CreateLogger<Startup>();
                        logger?.LogWarning($"PreErrorResponderMiddleware: Request IP Address: {ctx.HttpContext.Connection.RemoteIpAddress}");
                    }
                    catch { }

                    await next.Invoke();
                }
            };

            app.UseOcelot(configuration).Wait();

Locally in debug that middleware fires and it logs fine.

However, when I deploy to a Linux box I am only seeing Warn logs with the following (even though I have the log level set to Trace):

**[2022-09-16 09:21:41.1320][vmc-mercub][Warn] requestId: 0HMKNTNH0T00O:00000001, previousRequestId: no previous request id,** message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/api/v1.0/Parts/Inventory, request method: POST 

**[2022-09-16 09:21:41.1320][vmc-mercub][Warn] requestId: 0HMKNTNH0T00O:00000001, previousRequestId:** no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: **Unable to read data from the transport connection**: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.**GetResponse**(DownstreamContext context) errors found in **ResponderMiddleware**. **Setting error response for request path:/api/v1.0/Parts/Inventory,** request method: POST 

I would like to fix the exception - but I would like to understand why the Ocelot Middleware is not logging...

NOTE: I have middleware inserted prior to app.UseOcelot() as well that does logging prior to the PreErrorResponderMiddleware and it is also not logging.

Thoughts? Ideas?

**Comment by sergey-tomin** [comment]
I think you submitted this issue to a wrong repository

**Comment by clintcarter1999** [comment]
@sergey-tomin - Is this not the repo for Ocelot?

**Comment by clintcarter1999** [comment]
Oh, I see - yes, this is the wrong repo.
