### ISSUE TITLE
CSR with 0 angle bends

### ISSUE THREAD

**Issue by iagapov** [ocelot-collab/ocelot#2]
if a bend has 0 angle in the lattice csr crashes like so

Traceback (most recent call last):
  File "C:\workspace\p4-h\collective\cellA.py", line 192, in <module>
    navi.add_physics_proc(csr,lat.sequence[0], IDMARKER)
  File "c:\workspace\ocelot-collab\ocelot\cpbd\optics.py", line 1067, in add_physics_proc
    self.process_table.add_physics_proc(physics_proc, elem1, elem2)
  File "c:\workspace\ocelot-collab\ocelot\cpbd\optics.py", line 1041, in add_physics_proc
    physics_proc.prepare(self.lat)
  File "c:\workspace\ocelot-collab\ocelot\cpbd\csr.py", line 627, in prepare
    R = -elem.l/elem.angle
ZeroDivisionError: float division by zero

**Comment by sergey-tomin** [comment]
Fixed and committed to "dev" branch.
